ACCOUNTS=[
"GBQSSDCSKDH4H5XHR5X4CXMQBPREENE3Z3FDDSAZLCAIMPMCW7DWYPQN"
]

VERSION="1.0.0"

[DOCUMENTATION]
ORG_NAME="stellarflies"
ORG_URL="https://www.stellarflies.com/"
ORG_LOGO="https://www.stellarflies.com/images/stellarflies.png"
ORG_DESCRIPTION="stellarflies.com Your Stellar Marketplace that makes you fly high!"

[[CURRENCIES]]
code="FLY"
issuer="GBULORLSSGT2H2CDUNXC77KCUNYZH6UG7XGPYXBB65BO74ICXETVEMSF"
status="live"
display_decimals=4
name="FLY"
fixed_number=30000000000
desc="FLY is issued by Stellarflies Team."
conditions="Maximum supply of FLY is 30B tokens only"
image="https://Stellarflies.com/images/FLY.png"

[[CURRENCIES]]
code="BTC"
issuer="GABBPMH6EFP4QXL36ZVMQKMVE24XLS2DD74P6H76RV4OANOHCRL247DZ"
status="live"
display_decimals=4
name="BTC"
fixed_number=30000000000
desc="BTC is issued by Stellarflies Team."
conditions="Maximum supply of BTC is 30B tokens only"
image="https://Stellarflies.com/images/BTC.png"

[[CURRENCIES]]
code="TESLA"
issuer="GCLZEWDBRNOIKXLRJTVNIMG4KT6PFJEVTJI5J4ZW3OQNYZ5XYFC6UHQP"
status="live"
display_decimals=4
name="TESLA"
fixed_number=30000000000
desc="TESLA is issued by Stellarflies Team."
conditions="Maximum supply of TESLA is 30B tokens only"
image="https://Stellarflies.com/images/TESLA.png"

[[CURRENCIES]]
code="CHROME"
issuer="GCOHDYA4EFGVC774CYL5KLEHTYKGTG3YNCWLTFBJDA2MYFJUG7V5GBME"
status="live"
display_decimals=4
name="CHROME"
fixed_number=30000000000
desc="CHROME is issued by Stellarflies Team."
conditions="Maximum supply of CHROME is 30B tokens only"
image="https://Stellarflies.com/images/CHROME.png"

[[CURRENCIES]]
code="MICROSOFT"
issuer="GA7TVOAH6DU5VF6KKN7YIW5IHXGFSRYPI5A524L7PNXAYHOHGLRMSRYP"
status="live"
display_decimals=4
name="MICROSOFT"
fixed_number=30000000000
desc="MICROSOFT is issued by Stellarflies Team."
conditions="Maximum supply of MICROSOFT is 30B tokens only"
image="https://Stellarflies.com/images/MICROSOFT.png"

[[CURRENCIES]]
code="APPLE"
issuer="GDU7ESAX7EJQEHVLZPVFD4K6IVL2STSXOU2IRMZXB4RIWXE5DOMFWVZG"
status="live"
display_decimals=4
name="APPLE"
fixed_number=30000000000
desc="APPLE is issued by Stellarflies Team."
conditions="Maximum supply of APPLE is 30B tokens only"
image="https://Stellarflies.com/images/APPLE.png"

[[CURRENCIES]]
code="ASUS"
issuer="GCUZLYEQK6MK2YOXC7HIZNMV4RWO43AYRBUU4MDH3MJQEJMVJZ2TJBUU"
status="live"
display_decimals=4
name="ASUS"
fixed_number=30000000000
desc="ASUS is issued by Stellarflies Team."
conditions="Maximum supply of ASUS is 30B tokens only"
image="https://Stellarflies.com/images/ASUS.png"