ACCOUNTS=[
"GBQSSDCSKDH4H5XHR5X4CXMQBPREENE3Z3FDDSAZLCAIMPMCW7DWYPQN"
]

VERSION="1.0.0"

[DOCUMENTATION]
ORG_NAME="stellarflies"
ORG_URL="https://www.stellarflies.com/"
ORG_LOGO="https://www.stellarflies.com/images/stellarflies.png"
ORG_DESCRIPTION="stellarflies.com Your Stellar Marketplace that makes you fly high!"

[[CURRENCIES]]
code="FLY"
issuer="GBULORLSSGT2H2CDUNXC77KCUNYZH6UG7XGPYXBB65BO74ICXETVEMSF"
status="live"
display_decimals=4
name="FLY"
fixed_number=30000000000
desc="FLY is issued by Stellarflies Team."
conditions="Maximum supply of FLY is 30B tokens only"
image="https://Stellarflies.com/images/FLY.png"

[[CURRENCIES]]
code="BTC"
issuer="GABBPMH6EFP4QXL36ZVMQKMVE24XLS2DD74P6H76RV4OANOHCRL247DZ"
status="live"
display_decimals=4
name="BTC"
fixed_number=30000000000
desc="BTC is issued by Stellarflies Team."
conditions="Maximum supply of BTC is 30B tokens only"
image="https://Stellarflies.com/images/BTC.png"

[[CURRENCIES]]
code="TESLA"
issuer="GCLZEWDBRNOIKXLRJTVNIMG4KT6PFJEVTJI5J4ZW3OQNYZ5XYFC6UHQP"
status="live"
display_decimals=4
name="TESLA"
fixed_number=30000000000
desc="TESLA is issued by Stellarflies Team."
conditions="Maximum supply of TESLA is 30B tokens only"
image="https://Stellarflies.com/images/TESLA.png"

[[CURRENCIES]]
code="CHROME"
issuer="GCOHDYA4EFGVC774CYL5KLEHTYKGTG3YNCWLTFBJDA2MYFJUG7V5GBME"
status="live"
display_decimals=4
name="CHROME"
fixed_number=30000000000
desc="CHROME is issued by Stellarflies Team."
conditions="Maximum supply of CHROME is 30B tokens only"
image="https://Stellarflies.com/images/CHROME.png"

[[CURRENCIES]]
code="MICROSOFT"
issuer="GA7TVOAH6DU5VF6KKN7YIW5IHXGFSRYPI5A524L7PNXAYHOHGLRMSRYP"
status="live"
display_decimals=4
name="MICROSOFT"
fixed_number=30000000000
desc="MICROSOFT is issued by Stellarflies Team."
conditions="Maximum supply of MICROSOFT is 30B tokens only"
image="https://Stellarflies.com/images/MICROSOFT.png"

[[CURRENCIES]]
code="APPLE"
issuer="GDU7ESAX7EJQEHVLZPVFD4K6IVL2STSXOU2IRMZXB4RIWXE5DOMFWVZG"
status="live"
display_decimals=4
name="APPLE"
fixed_number=30000000000
desc="APPLE is issued by Stellarflies Team."
conditions="Maximum supply of APPLE is 30B tokens only"
image="https://Stellarflies.com/images/APPLE.png"

[[CURRENCIES]]
code="ASUS"
issuer="GCUZLYEQK6MK2YOXC7HIZNMV4RWO43AYRBUU4MDH3MJQEJMVJZ2TJBUU"
status="live"
display_decimals=4
name="ASUS"
fixed_number=30000000000
desc="ASUS is issued by Stellarflies Team."
conditions="Maximum supply of ASUS is 30B tokens only"
image="https://Stellarflies.com/images/ASUS.png"

[[CURRENCIES]]
code="SOL"
issuer="GC7OYN6UXGPQAJNHNQVHGSQGHX3ZVF6UPGGKOACXKF5EAZ7TTGRRGZ6Q"
status="live"
display_decimals=4
name="SOL"
fixed_number=30000000000
desc="SOL is issued by Stellarflies Team."
conditions="Maximum supply of SOL is 30B tokens only"
image="https://Stellarflies.com/images/SOL.png"

[[CURRENCIES]]
code="HP"
issuer="GDB6QEQEV4TWTJGADUSPLXR22UMLKRAJA44M4JGFBLQBKZ4IMI7K4BLH"
status="live"
display_decimals=4
name="HP"
fixed_number=30000000000
desc="HP is issued by Stellarflies Team."
conditions="Maximum supply of HP is 30B tokens only"
image="https://Stellarflies.com/images/HP.png"

[[CURRENCIES]]
code="ETH"
issuer="GDNDOKX6OE2BGUG6GF4A5HM5UAQZCROH5TSQCHGWATN6UWFL2VGC4YMY"
status="live"
display_decimals=4
name="ETH"
fixed_number=30000000000
desc="ETH is issued by Stellarflies Team."
conditions="Maximum supply of ETH is 30B tokens only"
image="https://Stellarflies.com/images/ETH.png"

[[CURRENCIES]]
code="ROG"
issuer="GDAMKXIGPBC5FDAXI66N3WSMT5QYV6Y7M3ANPLWO5WVMUZJQFXGQYJAT"
status="live"
display_decimals=4
name="ROG"
fixed_number=30000000000
desc="ROG is issued by Stellarflies Team."
conditions="Maximum supply of ROG is 30B tokens only"
image="https://Stellarflies.com/images/ROG.png"

[[CURRENCIES]]
code="ADA"
issuer="GBK7MRL6PPZSZ2V4NRESC5K5PWQF3LCCDBMC75OYCIVLIL2QTMYRAVJP"
status="live"
display_decimals=4
name="ADA"
fixed_number=30000000000
desc="ADA is issued by Stellarflies Team."
conditions="Maximum supply of ADA is 30B tokens only"
image="https://Stellarflies.com/images/ADA.png"

[[CURRENCIES]]
code="DELL"
issuer="GBEHGJXNSALWYX5YTHF5KUKNZC7VWP7YD2AHPRAWIPKCDHYGTRKZ7THD"
status="live"
display_decimals=4
name="DELL"
fixed_number=30000000000
desc="DELL is issued by Stellarflies Team."
conditions="Maximum supply of DELL is 30B tokens only"
image="https://Stellarflies.com/images/DELL.png"

[[CURRENCIES]]
code="DOT"
issuer="GDDFPXW23VPFSOE26SNPDTEQS6KFAKAQJ7RM4XGXJTOCKMTXG5752DPI"
status="live"
display_decimals=4
name="DOT"
fixed_number=30000000000
desc="DOT is issued by Stellarflies Team."
conditions="Maximum supply of DOT is 30B tokens only"
image="https://Stellarflies.com/images/DOT.png"

[[CURRENCIES]]
code="INTEL"
issuer="GB6MHIDY6ONLF3AH6IMHALXW6FQYZVPWFOBGRQTXHKKSZ7HSIWZ6HSFB"
status="live"
display_decimals=4
name="INTEL"
fixed_number=30000000000
desc="INTEL is issued by Stellarflies Team."
conditions="Maximum supply of INTEL is 30B tokens only"
image="https://Stellarflies.com/images/INTEL.png"

[[CURRENCIES]]
code="ALGO"
issuer="GAOQOQSVJZN6QXASUAU3ECLT437UY7JMZUITA4NJTAKGMD262JSY2YTH"
status="live"
display_decimals=4
name="ALGO"
fixed_number=30000000000
desc="ALGO is issued by Stellarflies Team."
conditions="Maximum supply of ALGO is 30B tokens only"
image="https://Stellarflies.com/images/ALGO.png"

[[CURRENCIES]]
code="FIREFOX"
issuer="GB3E64ESLWU45PMTYUL53QS7PV3WKSPV4PNNPPEGC6ECKNZ5LSXYVAJO"
status="live"
display_decimals=4
name="FIREFOX"
fixed_number=30000000000
desc="FIREFOX is issued by Stellarflies Team."
conditions="Maximum supply of FIREFOX is 30B tokens only"
image="https://Stellarflies.com/images/FIREFOX.png"

[[CURRENCIES]]
code="USDT"
issuer="GCTAGGXL3WKNOQAY73LIOHBXAWQNKKI2SWVZ4OOH7SBYILJK3U6XLBLG"
status="live"
display_decimals=4
name="USDT"
fixed_number=30000000000
desc="USDT is issued by Stellarflies Team."
conditions="Maximum supply of USDT is 30B tokens only"
image="https://Stellarflies.com/images/USDT.png"

[[CURRENCIES]]
code="BIRD"
issuer="GBYNL2SKOFVSVBUS2B3EXKBL67MQJD7OHSCJFOH6KWFBMGWENVH5UMQT"
status="live"
display_decimals=4
name="BIRD"
fixed_number=30000000000
desc="BIRD is issued by Stellarflies Team."
conditions="Maximum supply of BIRD is 30B tokens only"
image="https://Stellarflies.com/images/BIRD.png"

[[CURRENCIES]]
code="NETFLIX"
issuer="GBU5QJJG6LVD53XB7L3XBXNJX4SDUWXR4V2YRK77Z44W47TUBOWLQFTT"
status="live"
display_decimals=4
name="NETFLIX"
fixed_number=30000000000
desc="NETFLIX is issued by Stellarflies Team."
conditions="Maximum supply of NETFLIX is 30B tokens only"
image="https://Stellarflies.com/images/NETFLIX.png"

[[CURRENCIES]]
code="QUALCOMM"
issuer="GBFUR57W53UJRROXHJ63USSGDWSAGWPZSSWWRDHH3CFPVEPY63KL6S66"
status="live"
display_decimals=4
name="QUALCOMM"
fixed_number=30000000000
desc="QUALCOMM is issued by Stellarflies Team."
conditions="Maximum supply of QUALCOMM is 30B tokens only"
image="https://Stellarflies.com/images/QUALCOMM.png"

[[CURRENCIES]]
code="AIRPLANE"
issuer="GAHXCDHVJ2KCSAD6NL3ZKBXZXWQND5ACCBIQJQJDS5B46DPI2WO34J6I"
status="live"
display_decimals=4
name="AIRPLANE"
fixed_number=30000000000
desc="AIRPLANE is issued by Stellarflies Team."
conditions="Maximum supply of AIRPLANE is 30B tokens only"
image="https://Stellarflies.com/images/AIRPLANE.png"

[[CURRENCIES]]
code="KIN"
issuer="GBKHS4G2SP72HLE3BMAMY7UAT6KIMA5XC2BINQVZY4PDOJL5HFD3Q37E"
status="live"
display_decimals=4
name="KIN"
fixed_number=30000000000
desc="KIN is issued by Stellarflies Team."
conditions="Maximum supply of KIN is 30B tokens only"
image="https://Stellarflies.com/images/KIN.png"

[[CURRENCIES]]
code="NEURALINK"
issuer="GDWX6LGLAOCSRKTCDENTPRDZFTRNGXFE7NLZZVUTY3LFLPAATPDY6S4N"
status="live"
display_decimals=4
name="NEURALINK"
fixed_number=30000000000
desc="NEURALINK is issued by Stellarflies Team."
conditions="Maximum supply of NEURALINK is 30B tokens only"
image="https://Stellarflies.com/images/NEURALINK.png"
