ACCOUNTS=[
"GBQSSDCSKDH4H5XHR5X4CXMQBPREENE3Z3FDDSAZLCAIMPMCW7DWYPQN"
]

VERSION="1.0.0"

[DOCUMENTATION]
ORG_NAME="stellarflies"
ORG_URL="https://www.stellarflies.com/"
ORG_LOGO="https://www.stellarflies.com/images/stellarflies.png"
ORG_DESCRIPTION="stellarflies.com Your Stellar Marketplace that makes you fly high!"

[[CURRENCIES]]
code="FLY"
issuer="GBULORLSSGT2H2CDUNXC77KCUNYZH6UG7XGPYXBB65BO74ICXETVEMSF"
status="live"
display_decimals=4
name="FLY"
fixed_number=30000000000
desc="FLY is issued by Stellarflies Team."
conditions="Maximum supply of FLY is 30B tokens only"
image="https://Stellarflies.com/images/FLY.png"

[[CURRENCIES]]
code="BTC"
issuer="GABBPMH6EFP4QXL36ZVMQKMVE24XLS2DD74P6H76RV4OANOHCRL247DZ"
status="live"
display_decimals=4
name="BTC"
fixed_number=30000000000
desc="BTC is issued by Stellarflies Team."
conditions="Maximum supply of BTC is 30B tokens only"
image="https://Stellarflies.com/images/BTC.png"

[[CURRENCIES]]
code="TESLA"
issuer="GCLZEWDBRNOIKXLRJTVNIMG4KT6PFJEVTJI5J4ZW3OQNYZ5XYFC6UHQP"
status="live"
display_decimals=4
name="TESLA"
fixed_number=30000000000
desc="TESLA is issued by Stellarflies Team."
conditions="Maximum supply of TESLA is 30B tokens only"
image="https://Stellarflies.com/images/TESLA.png"

[[CURRENCIES]]
code="CHROME"
issuer="GCOHDYA4EFGVC774CYL5KLEHTYKGTG3YNCWLTFBJDA2MYFJUG7V5GBME"
status="live"
display_decimals=4
name="CHROME"
fixed_number=30000000000
desc="CHROME is issued by Stellarflies Team."
conditions="Maximum supply of CHROME is 30B tokens only"
image="https://Stellarflies.com/images/CHROME.png"

[[CURRENCIES]]
code="MICROSOFT"
issuer="GA7TVOAH6DU5VF6KKN7YIW5IHXGFSRYPI5A524L7PNXAYHOHGLRMSRYP"
status="live"
display_decimals=4
name="MICROSOFT"
fixed_number=30000000000
desc="MICROSOFT is issued by Stellarflies Team."
conditions="Maximum supply of MICROSOFT is 30B tokens only"
image="https://Stellarflies.com/images/MICROSOFT.png"

[[CURRENCIES]]
code="APPLE"
issuer="GDU7ESAX7EJQEHVLZPVFD4K6IVL2STSXOU2IRMZXB4RIWXE5DOMFWVZG"
status="live"
display_decimals=4
name="APPLE"
fixed_number=30000000000
desc="APPLE is issued by Stellarflies Team."
conditions="Maximum supply of APPLE is 30B tokens only"
image="https://Stellarflies.com/images/APPLE.png"

[[CURRENCIES]]
code="ASUS"
issuer="GCUZLYEQK6MK2YOXC7HIZNMV4RWO43AYRBUU4MDH3MJQEJMVJZ2TJBUU"
status="live"
display_decimals=4
name="ASUS"
fixed_number=30000000000
desc="ASUS is issued by Stellarflies Team."
conditions="Maximum supply of ASUS is 30B tokens only"
image="https://Stellarflies.com/images/ASUS.png"

[[CURRENCIES]]
code="SOL"
issuer="GC7OYN6UXGPQAJNHNQVHGSQGHX3ZVF6UPGGKOACXKF5EAZ7TTGRRGZ6Q"
status="live"
display_decimals=4
name="SOL"
fixed_number=30000000000
desc="SOL is issued by Stellarflies Team."
conditions="Maximum supply of SOL is 30B tokens only"
image="https://Stellarflies.com/images/SOL.png"

[[CURRENCIES]]
code="HP"
issuer="GDB6QEQEV4TWTJGADUSPLXR22UMLKRAJA44M4JGFBLQBKZ4IMI7K4BLH"
status="live"
display_decimals=4
name="HP"
fixed_number=30000000000
desc="HP is issued by Stellarflies Team."
conditions="Maximum supply of HP is 30B tokens only"
image="https://Stellarflies.com/images/HP.png"

[[CURRENCIES]]
code="ETH"
issuer="GDNDOKX6OE2BGUG6GF4A5HM5UAQZCROH5TSQCHGWATN6UWFL2VGC4YMY"
status="live"
display_decimals=4
name="ETH"
fixed_number=30000000000
desc="ETH is issued by Stellarflies Team."
conditions="Maximum supply of ETH is 30B tokens only"
image="https://Stellarflies.com/images/ETH.png"

[[CURRENCIES]]
code="ROG"
issuer="GDAMKXIGPBC5FDAXI66N3WSMT5QYV6Y7M3ANPLWO5WVMUZJQFXGQYJAT"
status="live"
display_decimals=4
name="ROG"
fixed_number=30000000000
desc="ROG is issued by Stellarflies Team."
conditions="Maximum supply of ROG is 30B tokens only"
image="https://Stellarflies.com/images/ROG.png"

[[CURRENCIES]]
code="ADA"
issuer="GBK7MRL6PPZSZ2V4NRESC5K5PWQF3LCCDBMC75OYCIVLIL2QTMYRAVJP"
status="live"
display_decimals=4
name="ADA"
fixed_number=30000000000
desc="ADA is issued by Stellarflies Team."
conditions="Maximum supply of ADA is 30B tokens only"
image="https://Stellarflies.com/images/ADA.png"

[[CURRENCIES]]
code="DELL"
issuer="GBEHGJXNSALWYX5YTHF5KUKNZC7VWP7YD2AHPRAWIPKCDHYGTRKZ7THD"
status="live"
display_decimals=4
name="DELL"
fixed_number=30000000000
desc="DELL is issued by Stellarflies Team."
conditions="Maximum supply of DELL is 30B tokens only"
image="https://Stellarflies.com/images/DELL.png"

[[CURRENCIES]]
code="DOT"
issuer="GDDFPXW23VPFSOE26SNPDTEQS6KFAKAQJ7RM4XGXJTOCKMTXG5752DPI"
status="live"
display_decimals=4
name="DOT"
fixed_number=30000000000
desc="DOT is issued by Stellarflies Team."
conditions="Maximum supply of DOT is 30B tokens only"
image="https://Stellarflies.com/images/DOT.png"

[[CURRENCIES]]
code="INTEL"
issuer="GB6MHIDY6ONLF3AH6IMHALXW6FQYZVPWFOBGRQTXHKKSZ7HSIWZ6HSFB"
status="live"
display_decimals=4
name="INTEL"
fixed_number=30000000000
desc="INTEL is issued by Stellarflies Team."
conditions="Maximum supply of INTEL is 30B tokens only"
image="https://Stellarflies.com/images/INTEL.png"

[[CURRENCIES]]
code="ALGO"
issuer="GAOQOQSVJZN6QXASUAU3ECLT437UY7JMZUITA4NJTAKGMD262JSY2YTH"
status="live"
display_decimals=4
name="ALGO"
fixed_number=30000000000
desc="ALGO is issued by Stellarflies Team."
conditions="Maximum supply of ALGO is 30B tokens only"
image="https://Stellarflies.com/images/ALGO.png"

[[CURRENCIES]]
code="FIREFOX"
issuer="GB3E64ESLWU45PMTYUL53QS7PV3WKSPV4PNNPPEGC6ECKNZ5LSXYVAJO"
status="live"
display_decimals=4
name="FIREFOX"
fixed_number=30000000000
desc="FIREFOX is issued by Stellarflies Team."
conditions="Maximum supply of FIREFOX is 30B tokens only"
image="https://Stellarflies.com/images/FIREFOX.png"

[[CURRENCIES]]
code="USDT"
issuer="GCTAGGXL3WKNOQAY73LIOHBXAWQNKKI2SWVZ4OOH7SBYILJK3U6XLBLG"
status="live"
display_decimals=4
name="USDT"
fixed_number=30000000000
desc="USDT is issued by Stellarflies Team."
conditions="Maximum supply of USDT is 30B tokens only"
image="https://Stellarflies.com/images/USDT.png"

[[CURRENCIES]]
code="BIRD"
issuer="GBYNL2SKOFVSVBUS2B3EXKBL67MQJD7OHSCJFOH6KWFBMGWENVH5UMQT"
status="live"
display_decimals=4
name="BIRD"
fixed_number=30000000000
desc="BIRD is issued by Stellarflies Team."
conditions="Maximum supply of BIRD is 30B tokens only"
image="https://Stellarflies.com/images/BIRD.png"

[[CURRENCIES]]
code="NETFLIX"
issuer="GBU5QJJG6LVD53XB7L3XBXNJX4SDUWXR4V2YRK77Z44W47TUBOWLQFTT"
status="live"
display_decimals=4
name="NETFLIX"
fixed_number=30000000000
desc="NETFLIX is issued by Stellarflies Team."
conditions="Maximum supply of NETFLIX is 30B tokens only"
image="https://Stellarflies.com/images/NETFLIX.png"

[[CURRENCIES]]
code="QUALCOMM"
issuer="GBFUR57W53UJRROXHJ63USSGDWSAGWPZSSWWRDHH3CFPVEPY63KL6S66"
status="live"
display_decimals=4
name="QUALCOMM"
fixed_number=30000000000
desc="QUALCOMM is issued by Stellarflies Team."
conditions="Maximum supply of QUALCOMM is 30B tokens only"
image="https://Stellarflies.com/images/QUALCOMM.png"

[[CURRENCIES]]
code="AIRPLANE"
issuer="GAHXCDHVJ2KCSAD6NL3ZKBXZXWQND5ACCBIQJQJDS5B46DPI2WO34J6I"
status="live"
display_decimals=4
name="AIRPLANE"
fixed_number=30000000000
desc="AIRPLANE is issued by Stellarflies Team."
conditions="Maximum supply of AIRPLANE is 30B tokens only"
image="https://Stellarflies.com/images/AIRPLANE.png"

[[CURRENCIES]]
code="KIN"
issuer="GBKHS4G2SP72HLE3BMAMY7UAT6KIMA5XC2BINQVZY4PDOJL5HFD3Q37E"
status="live"
display_decimals=4
name="KIN"
fixed_number=30000000000
desc="KIN is issued by Stellarflies Team."
conditions="Maximum supply of KIN is 30B tokens only"
image="https://Stellarflies.com/images/KIN.png"

[[CURRENCIES]]
code="NEURALINK"
issuer="GDWX6LGLAOCSRKTCDENTPRDZFTRNGXFE7NLZZVUTY3LFLPAATPDY6S4N"
status="live"
display_decimals=4
name="NEURALINK"
fixed_number=30000000000
desc="NEURALINK is issued by Stellarflies Team."
conditions="Maximum supply of NEURALINK is 30B tokens only"
image="https://Stellarflies.com/images/NEURALINK.png"

[[CURRENCIES]]
code="METAMASK"
issuer="GDZLD7QTU4MGHUZ4QKG6WI2IFVCWKSTNNHJFJI2A3XFQSKP7X6VAZX2G"
status="live"
display_decimals=4
name="METAMASK"
fixed_number=30000000000
desc="METAMASK is issued by Stellarflies Team."
conditions="Maximum supply of METAMASK is 30B tokens only"
image="https://Stellarflies.com/images/METAMASK.png"

[[CURRENCIES]]
code="SPOOKYSWAP"
issuer="GBUV7RU3DJXKDPE7BKUSJEXGYA4W2EDZQMOEOIFMSQVO7NGPMBGSCREC"
status="live"
display_decimals=4
name="SPOOKYSWAP"
fixed_number=30000000000
desc="SPOOKYSWAP is issued by Stellarflies Team."
conditions="Maximum supply of SPOOKYSWAP is 30B tokens only"
image="https://Stellarflies.com/images/SPOOKYSWAP.png"

[[CURRENCIES]]
code="UNISWAP"
issuer="GBBGBYISK2YAAD4EHEQUDVADJMEY2GSU3ZT5E7OSOHZ655RCU2CQXAUV"
status="live"
display_decimals=4
name="UNISWAP"
fixed_number=30000000000
desc="UNISWAP is issued by Stellarflies Team."
conditions="Maximum supply of UNISWAP is 30B tokens only"
image="https://Stellarflies.com/images/UNISWAP.png"

[[CURRENCIES]]
code="CHAINLINK"
issuer="GB6L6V3336NCS6QA6PUSRUVZKBRSJPATWBBLCWGOWMTIKNT45OHRW7P2"
status="live"
display_decimals=4
name="CHAINLINK"
fixed_number=30000000000
desc="CHAINLINK is issued by Stellarflies Team."
conditions="Maximum supply of CHAINLINK is 30B tokens only"
image="https://Stellarflies.com/images/CHAINLINK.png"

[[CURRENCIES]]
code="FANTOM"
issuer="GBL7ULYT5M24XK6DV4U2S35VPW7QIUONF55OCUNMDDMGACQV4QS2UKJD"
status="live"
display_decimals=4
name="FANTOM"
fixed_number=30000000000
desc="FANTOM is issued by Stellarflies Team."
conditions="Maximum supply of FANTOM is 30B tokens only"
image="https://Stellarflies.com/images/FANTOM.png"

[[CURRENCIES]]
code="SUSHISWAP"
issuer="GBA64GG27DWXFF5VELTOXRVUVDHJYXXOCQSJJ6WXOHSWTE6GSMMYPJQ4"
status="live"
display_decimals=4
name="SUSHISWAP"
fixed_number=30000000000
desc="SUSHISWAP is issued by Stellarflies Team."
conditions="Maximum supply of SUSHISWAP is 30B tokens only"
image="https://Stellarflies.com/images/SUSHISWAP.png"

[[CURRENCIES]]
code="LUNA"
issuer="GAWYZHL2EI3YAS6FHI6SEM62KXIFDGFANGZ2OTJX4JK6EDRG5NDG35R6"
status="live"
display_decimals=4
name="LUNA"
fixed_number=30000000000
desc="LUNA is issued by Stellarflies Team."
conditions="Maximum supply of LUNA is 30B tokens only"
image="https://Stellarflies.com/images/LUNA.png"

[[CURRENCIES]]
code="CURVE"
issuer="GBO3ENTGNSPB575XHUYJANBVMFWGR74PCPFDSKFNDEWMKSP5WQFWWIDP"
status="live"
display_decimals=4
name="CURVE"
fixed_number=30000000000
desc="CURVE is issued by Stellarflies Team."
conditions="Maximum supply of CURVE is 30B tokens only"
image="https://Stellarflies.com/images/CURVE.png"

[[CURRENCIES]]
code="OSMOSIS"
issuer="GBUIXSGKGEJDULIFE4POPZAEASMYCMDKQFHPLHYYV3WXU27CS3LA7VHF"
status="live"
display_decimals=4
name="OSMOSIS"
fixed_number=30000000000
desc="OSMOSIS is issued by Stellarflies Team."
conditions="Maximum supply of OSMOSIS is 30B tokens only"
image="https://Stellarflies.com/images/OSMOSIS.png"

[[CURRENCIES]]
code="SECRET"
issuer="GD2GO2CNJWHHZNJLUR54AV4RJ3OTJAOTEE4YHMRTBP7IJW5IF6H3M32U"
status="live"
display_decimals=4
name="SECRET"
fixed_number=30000000000
desc="SECRET is issued by Stellarflies Team."
conditions="Maximum supply of SECRET is 30B tokens only"
image="https://Stellarflies.com/images/SECRET.png"

[[CURRENCIES]]
code="SPIRITSWAP"
issuer="GAU7EYUDNKDCW4Y2UCSLQOS6PLIWBT67GMBLG6B66BJSAO4UO4TNRBBI"
status="live"
display_decimals=4
name="SPIRITSWAP"
fixed_number=30000000000
desc="SPIRITSWAP is issued by Stellarflies Team."
conditions="Maximum supply of SPIRITSWAP is 30B tokens only"
image="https://Stellarflies.com/images/SPIRITSWAP.png"

[[CURRENCIES]]
code="1INCH"
issuer="GCUMUYEBGHCFDGQBKGW74T3V2OXK3UB25REZP4ASKWNEQJN3YJE6T4Z6"
status="live"
display_decimals=4
name="1INCH"
fixed_number=30000000000
desc="1INCH is issued by Stellarflies Team."
conditions="Maximum supply of 1INCH is 30B tokens only"
image="https://Stellarflies.com/images/1INCH.png"