ACCOUNTS=[
"GBQSSDCSKDH4H5XHR5X4CXMQBPREENE3Z3FDDSAZLCAIMPMCW7DWYPQN"
]

VERSION="1.0.0"

[DOCUMENTATION]
ORG_NAME="stellarflies"
ORG_URL="https://www.stellarflies.com/"
ORG_LOGO="https://www.stellarflies.com/images/stellarflies.png"
ORG_DESCRIPTION="stellarflies.com Your Stellar Marketplace that makes you fly high!"