ACCOUNTS=[
"GBQSSDCSKDH4H5XHR5X4CXMQBPREENE3Z3FDDSAZLCAIMPMCW7DWYPQN"
]

VERSION="1.0.0"

[DOCUMENTATION]
ORG_NAME="stellarflies"
ORG_URL="https://www.stellarflies.com/"
ORG_LOGO="https://www.stellarflies.com/images/stellarflies.png"
ORG_DESCRIPTION="stellarflies.com Your Stellar Marketplace that makes you fly high!"

[[CURRENCIES]]
code="FLY"
issuer="GBULORLSSGT2H2CDUNXC77KCUNYZH6UG7XGPYXBB65BO74ICXETVEMSF"
status="live"
display_decimals=4
name="FLY"
fixed_number=30000000000
desc="FLY is issued by Stellarflies Team."
conditions="Maximum supply of FLY is 30B tokens only"
image="https://Stellarflies.com/images/FLY.png"
